routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/dashboard', 'HomeController@dashboard')->name('home');

    Route::resource('users', 'UserController');
    Route::resource('suppliers', 'SupplierController');
    Route::get('materials/report', 'MaterialController@report')->name('materials.report');
    Route::resource('materials', 'MaterialController');
    Route::resource('cars', 'CarController');
    Route::group(['prefix' => 'suppliers'], function () {
        Route::get('/{supplier}/materials', 'MaterialPriceController@index')->name('suppliers.materials.index');
        Route::get('/{supplier}/materials/create', 'MaterialPriceController@create')->name('suppliers.materials.create');
        Route::post('/{supplier}/materials/store', 'MaterialPriceController@store')->name('suppliers.materials.store');
        Route::get('/{supplier}/materials/{material}/edit', 'MaterialPriceController@edit')->name('suppliers.materials.edit');
        Route::put('/{supplier}/materials{material}/update', 'MaterialPriceController@update')->name('suppliers.materials.update');
        Route::delete('/{supplier}/materials/{material}', 'MaterialPriceController@destroy')->name('suppliers.materials.delete');
    });

    Route::get('products/report', 'ProductController@report')->name('products.report');
    Route::resource('products', 'ProductController');

    Route::get('orders/report', 'OrderController@report')->name('orders.report');
    Route::resource('orders', 'OrderController');
    Route::get('/orders/{order}/report', 'OrderController@printDetail')->name('orders.show.report');
    Route::get('/orders/{order}/toggle-status', 'OrderController@toggleStatus')->name('orders.toggle_status');

    Route::get('productions/report', 'ProductionController@report')->name('productions.report');
    Route::resource('productions', 'ProductionController');
    Route::get('/productions/{production}/report', 'ProductionController@printDetail')->name('productions.show.report');
    Route::get('/productions/{production}/toggle-status', 'ProductionController@toggleStatus')->name('productions.toggle_status');

    Route::get('purchases/report', 'PurchaseController@report')->name('purchases.report');
    Route::resource('purchases', 'PurchaseController');
    Route::get('/purchases/{purchase}/report', 'PurchaseController@printDetail')->name('purchases.show.report');
    Route::get('/purchases/{purchase}/toggle-status', 'PurchaseController@toggleStatus')->name('purchases.toggle_status');

    Route::get('customers', 'CustomerController@index')->name('customers.index');
    Route::get('customers/report', 'CustomerController@report')->name('customers.report');
    Route::get('customers/{customer}', 'CustomerController@show')->name('customers.show');
    Route::get('customers/{customer}/edit', 'CustomerController@edit')->name('customers.edit');
    Route::get('customers/{customer}/update', 'CustomerController@update')->name('customers.update');

    Route::get('deliveries/report', 'DeliveryController@report')->name('deliveries.report');
    Route::resource('deliveries', 'DeliveryController');
    Route::get('deliveries/{delivery}/report', 'DeliveryController@printDetail')->name('deliveries.show.report');
});

resources/views/layouts/partials/_footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Supply Chain Management
    </div>
    <div class="footer-right">
        Copyright &copy; 2020 <div class="bullet"></div> PT. Barokah Kreasi Solusindo
    </div>
</footer>

resources/views/layouts/partials/_navbar.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
        </ul>
    </form>
    <ul class="navbar-nav navbar-right">
        {{-- <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
            <div class="dropdown-header">Messages
                <div class="float-right">
                <a href="#">Mark All As Read</a>
                </div>
            </div>
            <div class="dropdown-list-content dropdown-list-message">
                <a href="#" class="dropdown-item dropdown-item-unread">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="../assets/img/avatar/avatar-1.png" class="rounded-circle">
                    <div class="is-online"></div>
                </div>
                <div class="dropdown-item-desc">
                    <b>Kusnaedi</b>
                    <p>Hello, Bro!</p>
                    <div class="time">10 Hours Ago</div>
                </div>
                </a>
                <a href="#" class="dropdown-item dropdown-item-unread">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="../assets/img/avatar/avatar-2.png" class="rounded-circle">
                </div>
                <div class="dropdown-item-desc">
                    <b>Dedik Sugiharto</b>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    <div class="time">12 Hours Ago</div>
                </div>
                </a>
                <a href="#" class="dropdown-item dropdown-item-unread">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="../assets/img/avatar/avatar-3.png" class="rounded-circle">
                    <div class="is-online"></div>
                </div>
                <div class="dropdown-item-desc">
                    <b>Agung Ardiansyah</b>
                    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    <div class="time">12 Hours Ago</div>
                </div>
                </a>
                <a href="#" class="dropdown-item">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="../assets/img/avatar/avatar-4.png" class="rounded-circle">
                </div>
                <div class="dropdown-item-desc">
                    <b>Ardian Rahardiansyah</b>
                    <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>
                    <div class="time">16 Hours Ago</div>
                </div>
                </a>
                <a href="#" class="dropdown-item">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="../assets/img/avatar/avatar-5.png" class="rounded-circle">
                </div>
                <div class="dropdown-item-desc">
                    <b>Alfa Zulkarnain</b>
                    <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
                    <div class="time">Yesterday</div>
                </div>
                </a>
            </div>
            <div class="dropdown-footer text-center">
                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
            </div>
            </div>
        </li>
        <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
            <div class="dropdown-header">Notifications
                <div class="float-right">
                <a href="#">Mark All As Read</a>
                </div>
            </div>
            <div class="dropdown-list-content dropdown-list-icons">
                <a href="#" class="dropdown-item dropdown-item-unread">
                <div class="dropdown-item-icon bg-primary text-white">
                    <i class="fas fa-code"></i>
                </div>
                <div class="dropdown-item-desc">
                    Template update is available now!
                    <div class="time text-primary">2 Min Ago</div>
                </div>
                </a>
                <a href="#" class="dropdown-item">
                <div class="dropdown-item-icon bg-info text-white">
                    <i class="far fa-user"></i>
                </div>
                <div class="dropdown-item-desc">
                    <b>You</b> and <b>Dedik Sugiharto</b> are now friends
                    <div class="time">10 Hours Ago</div>
                </div>
                </a>
                <a href="#" class="dropdown-item">
                <div class="dropdown-item-icon bg-success text-white">
                    <i class="fas fa-check"></i>
                </div>
                <div class="dropdown-item-desc">
                    <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                    <div class="time">12 Hours Ago</div>
                </div>
                </a>
                <a href="#" class="dropdown-item">
                <div class="dropdown-item-icon bg-danger text-white">
                    <i class="fas fa-exclamation-triangle"></i>
                </div>
                <div class="dropdown-item-desc">
                    Low disk space. Let's clean it!
                    <div class="time">17 Hours Ago</div>
                </div>
                </a>
                <a href="#" class="dropdown-item">
                <div class="dropdown-item-icon bg-info text-white">
                    <i class="fas fa-bell"></i>
                </div>
                <div class="dropdown-item-desc">
                    Welcome to Stisla template!
                    <div class="time">Yesterday</div>
                </div>
                </a>
            </div>
            <div class="dropdown-footer text-center">
                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
            </div>
            </div>
        </li> --}}
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{{ \Auth::user()->photoUrl ?? asset('stisla-2.2.0/dist/assets/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Hi, {{ request()->user()->name }}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
            {{-- <div class="dropdown-title">Logged in 5 min ago</div> --}}
            {{-- <a href="features-profile.html" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profile
            </a>
            <a href="features-activities.html" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Activities
            </a>
            <a href="features-settings.html" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Settings
            </a> --}}
            {{-- <div class="dropdown-divider"></div> --}}
                <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Logout
            </a>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/partials/_sidebar.blade.php
@php
$notifOrder = 0;
$notifProduction = 0;
$notifPurchase = 0;
$notifDelivery = 0;
@endphp

@switch(\Auth::user()->role)
    @case("administrator")
        @php
            $notifOrder = \App\Models\Order::where('status', 0)->count();
            $notifProduction = \App\Models\Production::where('status', 2)->count();
            $notifPurchase = \App\Models\Production::where('status', 0)->count();
            $notifDelivery = \App\Models\Order::where('status', 2)->count();
        @endphp
        @break
    @case("bag_admin")
        @php
            $notifDelivery = \App\Models\Order::where('status', 2)->count();
        @endphp

        @break
    @case("bag_gudang")
        @php
            $notifPurchase = \App\Models\Production::where('status', 0)->count()
        @endphp

        @break
    @case("bag_produksi")
        @php
            $notifOrder = \App\Models\Order::where('status', 0)->count();
            $notifProduction = \App\Models\Production::where('status', 2)->count();
        @endphp
        @break
    @default

@endswitch

<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{ route('index') }}"><img src="{{ asset('logo.png') }}" class="logo-l"></a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ route('index') }}"><img src="{{ asset('icon.png') }}" class="logo-m"></a>
        </div>
        <ul class="sidebar-menu">
            <li class="{{ request()->is('/') ? 'active' : '' }}"><a class="nav-link" href="{{ route('home') }}"><i class="fas fa-th-large"></i> <span>Dashboard</span></a></li>
@php
    $user = \Auth::user();
@endphp
            {{-- <li class="menu-header">Data Master</li> --}}
            @if ($user->role == 'administrator' || $user->role == 'admin')
                <li class="{{ request()->is('users*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('users.index') }}"><i class="fas fa-users"></i> <span>Data Pegawai</span></a></li>
                <li class="{{ request()->is('cars*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('cars.index') }}"><i class="fas fa-truck"></i> <span>Data Mobil</span></a></li>
            {{-- @endif

            @if ($user->role == 'administrator' || $user->role == 'admin') --}}
                <li class="{{ request()->is('customers*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('customers.index') }}"><i class="fas fa-user"></i> <span>Data Pelanggan</span></a></li>
            @endif

            @if ($user->role == 'administrator'|| $user->role == 'admin' || $user->role == 'bag_gudang')
                <li class="{{ request()->is('suppliers*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('suppliers.index') }}"><i class="fas fa-address-card"></i> <span>Data Supplier</span></a></li>
            @endif

            @if ($user->role == 'administrator'|| $user->role == 'bag_gudang')
                <li class="{{ request()->is('materials*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('materials.index') }}"><i class="fas fa-fill-drip"></i> <span>Data Bahan Baku</span></a></li>
            @endif

            @if ($user->role == 'administrator' || $user->role == 'bag_produksi')
                <li class="{{ request()->is('products*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('products.index') }}"><i class="fas fa-spray-can"></i> <span>Data Produk</span></a></li>
            @endif

            @if ($user->role == 'administrator' || $user->role == 'bag_produksi' || $user->role == 'admin')
                <li class="{{ request()->is('orders*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('orders.index') }}">
                        <i class="fas fa-shopping-cart"></i>
                        <span>Pesanan</span>
                        @if($notifOrder > 0)
                        <span class="badge badge-warning" style="width: 30px;">{{ $notifOrder }}</span>
                        @endif
                    </a>
                </li>
            @endif

            @if ($user->role == 'administrator' || $user->role == 'bag_produksi')
                <li class="{{ request()->is('productions*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('productions.index') }}">
                        <i class="fas fa-flask"></i>
                        <span>Produksi</span>
                        @if($notifProduction > 0)
                        <span class="badge badge-warning" style="width: 30px;">{{ $notifProduction }}</span>
                        @endif
                    </a>
                </li>
            @endif

            @if ($user->role == 'administrator' || $user->role == 'bag_gudang')
                <li class="{{ request()->is('purchases*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('purchases.index') }}">
                        <i class="fas fa-dolly-flatbed"></i>
                        <span>Pengadaaan Bahan Baku</span>
                        @if($notifPurchase > 0)
                        <span class="badge badge-warning" style="width: 30px;">{{ $notifPurchase }}</span>
                        @endif
                    </a>
                </li>
            @endif

            @if ($user->role == 'administrator' || $user->role == 'admin')
                <li class="{{ request()->is('deliveries*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('deliveries.index') }}">
                        <i class="fas fa-shipping-fast"></i>
                        <span>Pengiriman</span>
                        @if($notifDelivery > 0)
                        <span class="badge badge-warning" style="width: 30px;">{{ $notifDelivery }}</span>
                        @endif
                    </a>
                </li>
            @endif


            {{-- <li class="nav-item dropdown">
                <a href="#" class="nav-link has-d ropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Data Master</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="layout-default.html"><i class="fas fa-users"></i> Data Pegawai</a></li>
                    <li><a class="nav-link" href="layout-transparent.html"><i class="fas fa-bong"></i> Data Produk</a></li>
                    <li><a class="nav-link" href="layout-top-navigation.html"><i class="fas fa-address-card"></i> Data Supplier</a></li>

                </ul>
            </li> --}}
        </ul>
    </aside>
</div>