routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/dashboard', 'HomeController@dashboard')->name('home');

    Route::resource('users', 'UserController');
    Route::resource('suppliers', 'SupplierController');
    Route::get('materials/report', 'MaterialController@report')->name('materials.report');
    Route::resource('materials', 'MaterialController');
    Route::resource('cars', 'CarController');
    Route::group(['prefix' => 'suppliers'], function () {
        Route::get('/{supplier}/materials', 'MaterialPriceController@index')->name('suppliers.materials.index');
        Route::get('/{supplier}/materials/create', 'MaterialPriceController@create')->name('suppliers.materials.create');
        Route::post('/{supplier}/materials/store', 'MaterialPriceController@store')->name('suppliers.materials.store');
        Route::get('/{supplier}/materials/{material}/edit', 'MaterialPriceController@edit')->name('suppliers.materials.edit');
        Route::put('/{supplier}/materials{material}/update', 'MaterialPriceController@update')->name('suppliers.materials.update');
        Route::delete('/{supplier}/materials/{material}', 'MaterialPriceController@destroy')->name('suppliers.materials.delete');
    });

    Route::get('products/report', 'ProductController@report')->name('products.report');
    Route::resource('products', 'ProductController');

    Route::get('orders/report', 'OrderController@report')->name('orders.report');
    Route::resource('orders', 'OrderController');
    Route::get('/orders/{order}/report', 'OrderController@printDetail')->name('orders.show.report');
    Route::get('/orders/{order}/toggle-status', 'OrderController@toggleStatus')->name('orders.toggle_status');

    Route::get('productions/report', 'ProductionController@report')->name('productions.report');
    Route::resource('productions', 'ProductionController');
    Route::get('/productions/{production}/report', 'ProductionController@printDetail')->name('productions.show.report');
    Route::get('/productions/{production}/toggle-status', 'ProductionController@toggleStatus')->name('productions.toggle_status');

    Route::get('purchases/report', 'PurchaseController@report')->name('purchases.report');
    Route::resource('purchases', 'PurchaseController');
    Route::get('/purchases/{purchase}/report', 'PurchaseController@printDetail')->name('purchases.show.report');
    Route::get('/purchases/{purchase}/toggle-status', 'PurchaseController@toggleStatus')->name('purchases.toggle_status');

    Route::get('customers', 'CustomerController@index')->name('customers.index');
    Route::get('customers/report', 'CustomerController@report')->name('customers.report');
    Route::get('customers/{customer}', 'CustomerController@show')->name('customers.show');
    Route::get('customers/{customer}/edit', 'CustomerController@edit')->name('customers.edit');
    Route::get('customers/{customer}/update', 'CustomerController@update')->name('customers.update');

    Route::get('deliveries/report', 'DeliveryController@report')->name('deliveries.report');
    Route::resource('deliveries', 'DeliveryController');
    Route::get('deliveries/{delivery}/report', 'DeliveryController@printDetail')->name('deliveries.show.report');
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};

class Supplier extends Model
{
    use SoftDeletes;

    public function materials()
    {
        return $this->hasMany(MaterialPrice::class);
    }

    public function generateCode()
    {
        $last = Self::latest()->first();
        $code = 'S';
        if(is_null($last)){
            $code .= '001';
        }else{
            $lastNum = (int) substr($last->code, 1, 3);
            $code .= sprintf("%'03d", $lastNum+1);
        }

        return $code;
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Models\Supplier;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    public function index(Request $request)
    {
        $suppliers = Supplier::latest();

        if($request->has('search')){
            $query = '%'.$request->search.'%';
            $suppliers->where('name', 'LIKE', $query);
        }

        $suppliers = $suppliers->paginate(config('app.per_page'));

        return view('supplier.index', compact('suppliers'));
    }

    public function create()
    {
        return view('supplier.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:3',
            'address' => 'required|string|min:10',
            'phone' => 'required|string|numeric'
        ], [], [
            'name' => 'nama supplier',
            'address' => 'alamat',
            'phone' => 'nomor telepon'
        ]);

        $supplier = new Supplier;
        $supplier->name = $request->name;
        $supplier->code = $supplier->generateCode();
        $supplier->address = $request->address;
        $supplier->phone = $request->phone;
        $supplier->save();

        return redirect()->route('suppliers.index')->with('alert-success', 'Berhasil menambah data supplier');
    }

    public function show(Supplier $supplier)
    {
        return view('supplier.edit', compact('supplier'));
    }

    public function edit(Supplier $supplier)
    {
        return view('supplier.edit', compact('supplier'));
    }

    public function update(Request $request, Supplier $supplier)
    {
        $this->validate($request, [
            'name' => 'required|string|min:3',
            'address' => 'required|string|min:10',
            'phone' => 'required|string|numeric'
        ], [], [
            'name' => 'nama supplier',
            'address' => 'alamat',
            'phone' => 'nomor telepon'
        ]);

        $supplier->name = $request->name;
        $supplier->address = $request->address;
        $supplier->phone = $request->phone;
        $supplier->save();

        return redirect()->route('suppliers.index')->with('alert-success', 'Berhasil mengubah data supplier');
    }

    public function destroy(Supplier $supplier)
    {
        $supplier->delete();
        return redirect()->route('suppliers.index')->with('alert-success', 'Berhasil menghapus data supplier');
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('suppliers.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Tambah Supplier</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Supplier</a></div>
          <div class="breadcrumb-item">Tambah Supplier</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data Supplier Baru</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('suppliers.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">Nama Supplier</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('name') }}" name="name" class="@error('name') is-invalid @enderror form-control">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">Alamat</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('address') }}" name="address" class="@error('address') is-invalid @enderror form-control">
                            @error('address')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">Telepon</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('phone') }}" name="phone" class="@error('phone') is-invalid @enderror form-control">
                            @error('phone')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/supplier/edit.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('suppliers.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Edit Supplier</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Supplier</a></div>
          <div class="breadcrumb-item">Edit Supplier</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data Supplier</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('suppliers.update', $supplier) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">Nama Supplier</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('name', $supplier->name) }}" name="name" class="@error('name') is-invalid @enderror form-control">
                            @error('name')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">Alamat</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('address', $supplier->address) }}" name="address" class="@error('address') is-invalid @enderror form-control">
                            @error('address')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">Telepon</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('phone', $supplier->phone) }}" name="phone" class="@error('phone') is-invalid @enderror form-control">
                            @error('phone')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/supplier/index.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Supplier</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Supplier</a></div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Daftar Supplier</h4>
              </div>
              <div class="card-body">
                <div class="float-left">
                    <a href="{{ route('suppliers.create') }}" class="btn btn-primary">Tambah Supplier</a>
                </div>
                <div class="float-right">
                  <form action="" method="GET">
                    <div class="input-group">
                      <input type="text" class="form-control" name="search" placeholder="Search">
                      <div class="input-group-append">
                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="clearfix mb-3"></div>

                <div class="table-responsive">
                  <table class="table table-striped">
                    <tr>
                      <th>No</th>
                      <th>Kode Supplier</th>
                      <th>Nama</th>
                      <th>Telephone</th>
                      <th>Alamat</th>
                      <th>#</th>
                    </tr>
                    @forelse ($suppliers as $item)
                    <tr>
                        <td>{{ (($suppliers->currentPage()-1) * $suppliers->perPage()) + $loop->iteration }}</td>
                        <td>{{ $item->code }}</td>
                        <td>{{ $item->name }}</td>
                        <td>{{ $item->phone }}</td>
                        <td>{{ $item->address }}</td>
                        <td>
                            <a href="{{ route('suppliers.materials.index', $item) }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Katalog Bahan Baku"> <span class="fas fa-fill-drip"></span></a>
                            <a href="{{ route('suppliers.edit', $item) }}" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="Edit Supplier"> <span class="fa fa-edit"></span></a>
                            <span data-title="{{ $item->name }}" href="{{ route('suppliers.destroy', $item) }}" class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip" data-placement="top" title="Hapus Supplier"> <span class="fa fa-trash"></span></span>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" align="center">
                            <div class="empty-state" data-height="400" style="height: 400px;">
                                <div class="empty-state-icon">
                                  <i class="fas fa-question"></i>
                                </div>
                                <h2>Data Tidak Ditemukan</h2>
                                <p class="lead">
                                  Maaf kami tidak dapat menemukan data.
                                </p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
                <div class="float-right">
                  {{ $suppliers->links() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')

<script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        swal({
          title: "Anda yakin akan menghapus Supplier bernama "+ title +" ?",
          text: "Setelah dihapus data tidak dapat dikembalikan !",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        });
    });
    </script>
@endsection