routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/dashboard', 'HomeController@dashboard')->name('home');

    Route::resource('users', 'UserController');
    Route::resource('suppliers', 'SupplierController');
    Route::get('materials/report', 'MaterialController@report')->name('materials.report');
    Route::resource('materials', 'MaterialController');
    Route::resource('cars', 'CarController');
    Route::group(['prefix' => 'suppliers'], function () {
        Route::get('/{supplier}/materials', 'MaterialPriceController@index')->name('suppliers.materials.index');
        Route::get('/{supplier}/materials/create', 'MaterialPriceController@create')->name('suppliers.materials.create');
        Route::post('/{supplier}/materials/store', 'MaterialPriceController@store')->name('suppliers.materials.store');
        Route::get('/{supplier}/materials/{material}/edit', 'MaterialPriceController@edit')->name('suppliers.materials.edit');
        Route::put('/{supplier}/materials{material}/update', 'MaterialPriceController@update')->name('suppliers.materials.update');
        Route::delete('/{supplier}/materials/{material}', 'MaterialPriceController@destroy')->name('suppliers.materials.delete');
    });

    Route::get('products/report', 'ProductController@report')->name('products.report');
    Route::resource('products', 'ProductController');

    Route::get('orders/report', 'OrderController@report')->name('orders.report');
    Route::resource('orders', 'OrderController');
    Route::get('/orders/{order}/report', 'OrderController@printDetail')->name('orders.show.report');
    Route::get('/orders/{order}/toggle-status', 'OrderController@toggleStatus')->name('orders.toggle_status');

    Route::get('productions/report', 'ProductionController@report')->name('productions.report');
    Route::resource('productions', 'ProductionController');
    Route::get('/productions/{production}/report', 'ProductionController@printDetail')->name('productions.show.report');
    Route::get('/productions/{production}/toggle-status', 'ProductionController@toggleStatus')->name('productions.toggle_status');

    Route::get('purchases/report', 'PurchaseController@report')->name('purchases.report');
    Route::resource('purchases', 'PurchaseController');
    Route::get('/purchases/{purchase}/report', 'PurchaseController@printDetail')->name('purchases.show.report');
    Route::get('/purchases/{purchase}/toggle-status', 'PurchaseController@toggleStatus')->name('purchases.toggle_status');

    Route::get('customers', 'CustomerController@index')->name('customers.index');
    Route::get('customers/report', 'CustomerController@report')->name('customers.report');
    Route::get('customers/{customer}', 'CustomerController@show')->name('customers.show');
    Route::get('customers/{customer}/edit', 'CustomerController@edit')->name('customers.edit');
    Route::get('customers/{customer}/update', 'CustomerController@update')->name('customers.update');

    Route::get('deliveries/report', 'DeliveryController@report')->name('deliveries.report');
    Route::resource('deliveries', 'DeliveryController');
    Route::get('deliveries/{delivery}/report', 'DeliveryController@printDetail')->name('deliveries.show.report');
});

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    //
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Car;
use Illuminate\Http\Request;

class CarController extends Controller
{
    public function index(Request $request)
    {
        $cars = Car::latest();

        $cars = $cars->paginate(config('app.per_page'));

        return view('car.index', compact('cars'));
    }

    public function create()
    {
        return view('car.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'no_pol' => 'required|string|min:3',
            'merk' => 'required|string',
        ]);

        $car = new Car;
        $car->no_pol = $request->no_pol;
        $car->merk = $request->merk;
        $car->save();

        return redirect()->route('cars.index')->with('alert-success', 'Berhasil menambah data mobil');
    }

    public function show(Car $car)
    {
        return view('car.edit', compact('car'));
    }

    public function edit(Car $car)
    {
        return view('car.edit', compact('car'));
    }

    public function update(Request $request, Car $car)
    {
        $this->validate($request, [
            'no_pol' => 'required|string|min:3',
            'merk' => 'required|string',
        ], [], [
            'merk' => 'merek'
        ]);

        $car->no_pol = $request->no_pol;
        $car->merk = $request->merk;
        $car->save();

        return redirect()->route('cars.index')->with('alert-success', 'Berhasil mengubah data mobil');
    }

    public function destroy(Car $car)
    {
        $car->delete();
        return redirect()->route('cars.index')->with('alert-success', 'Berhasil menghapus data mobil');
    }
}

resources/views/car/create.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('cars.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Tambah Mobil</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Mobil</a></div>
          <div class="breadcrumb-item">Tambah Mobil</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data Mobil Baru</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('cars.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">No Pol</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('no_pol') }}" name="no_pol" class="@error('no_pol') is-invalid @enderror form-control">
                            @error('no_pol')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">Merek</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('merk') }}" name="merk" class="@error('merk') is-invalid @enderror form-control">
                            @error('merk')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/car/edit.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('cars.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Edit Mobil</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Mobil</a></div>
          <div class="breadcrumb-item">Edit Mobil</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Data Mobil</h4>
              </div>
              <div class="card-body">
                <form class="form" action="{{ route('cars.update', $car) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">No Pol</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('no_pol', $car->no_pol) }}" name="no_pol" class="@error('no_pol') is-invalid @enderror form-control">
                            @error('no_pol')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right">Merek</label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <input type="text" value="{{ old('merk', $car->merk) }}" name="merk" class="@error('merk') is-invalid @enderror form-control">
                            @error('merk')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row align-items-center">
                        <label for="site-title" class="form-control-label col-sm-3 text-md-right"></label>
                        <div class="col-sm-6 col-md-9 col-lg-6">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/car/index.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Mobil</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Mobil</a></div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Daftar Mobil</h4>
              </div>
              <div class="card-body">
                <div class="float-left">
                    <a href="{{ route('cars.create') }}" class="btn btn-primary">Tambah Mobil</a>
                </div>

                <div class="clearfix mb-3"></div>

                <div class="table-responsive">
                  <table class="table table-striped">
                    <tr>
                      <th>No</th>
                      <th>No Pol</th>
                      <th>Merek</th>
                      <th>#</th>
                    </tr>
                    @forelse ($cars as $item)
                    <tr>
                        <td>{{ (($cars->currentPage()-1) * $cars->perPage()) + $loop->iteration }}</td>
                        <td>{{ $item->no_pol }}</td>
                        <td>{{ $item->merk }}</td>
                        <td>
                            {{-- <a href="" class="btn btn-sm btn-info"> <span class="fa fa-eye"></span></a> --}}
                            <a href="{{ route('cars.edit', $item) }}" class="btn btn-sm btn-warning"> <span class="fa fa-edit"></span></a>
                            <span data-title="{{ $item->no_pol }}" href="{{ route('cars.destroy', $item) }}" class="btn btn-sm btn-danger btn-delete"> <span class="fa fa-trash"></span></span>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" align="center">
                            <div class="empty-state" data-height="400" style="height: 400px;">
                                <div class="empty-state-icon">
                                  <i class="fas fa-question"></i>
                                </div>
                                <h2>Data Tidak Ditemukan</h2>
                                <p class="lead">
                                  Maaf kami tidak dapat menemukan data.
                                </p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
                <div class="float-right">
                  {{ $cars->links() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')

<script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        swal({
          title: "Anda yakin akan menghapus kendaraan "+ title +" ?",
          text: "Setelah dihapus data tidak dapat dikembalikan !",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        });
    });
    </script>
@endsection