routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('index');
    Route::get('/dashboard', 'HomeController@dashboard')->name('home');

    Route::resource('users', 'UserController');
    Route::resource('suppliers', 'SupplierController');
    Route::get('materials/report', 'MaterialController@report')->name('materials.report');
    Route::resource('materials', 'MaterialController');
    Route::resource('cars', 'CarController');
    Route::group(['prefix' => 'suppliers'], function () {
        Route::get('/{supplier}/materials', 'MaterialPriceController@index')->name('suppliers.materials.index');
        Route::get('/{supplier}/materials/create', 'MaterialPriceController@create')->name('suppliers.materials.create');
        Route::post('/{supplier}/materials/store', 'MaterialPriceController@store')->name('suppliers.materials.store');
        Route::get('/{supplier}/materials/{material}/edit', 'MaterialPriceController@edit')->name('suppliers.materials.edit');
        Route::put('/{supplier}/materials{material}/update', 'MaterialPriceController@update')->name('suppliers.materials.update');
        Route::delete('/{supplier}/materials/{material}', 'MaterialPriceController@destroy')->name('suppliers.materials.delete');
    });

    Route::get('products/report', 'ProductController@report')->name('products.report');
    Route::resource('products', 'ProductController');

    Route::get('orders/report', 'OrderController@report')->name('orders.report');
    Route::resource('orders', 'OrderController');
    Route::get('/orders/{order}/report', 'OrderController@printDetail')->name('orders.show.report');
    Route::get('/orders/{order}/toggle-status', 'OrderController@toggleStatus')->name('orders.toggle_status');

    Route::get('productions/report', 'ProductionController@report')->name('productions.report');
    Route::resource('productions', 'ProductionController');
    Route::get('/productions/{production}/report', 'ProductionController@printDetail')->name('productions.show.report');
    Route::get('/productions/{production}/toggle-status', 'ProductionController@toggleStatus')->name('productions.toggle_status');

    Route::get('purchases/report', 'PurchaseController@report')->name('purchases.report');
    Route::resource('purchases', 'PurchaseController');
    Route::get('/purchases/{purchase}/report', 'PurchaseController@printDetail')->name('purchases.show.report');
    Route::get('/purchases/{purchase}/toggle-status', 'PurchaseController@toggleStatus')->name('purchases.toggle_status');

    Route::get('customers', 'CustomerController@index')->name('customers.index');
    Route::get('customers/report', 'CustomerController@report')->name('customers.report');
    Route::get('customers/{customer}', 'CustomerController@show')->name('customers.show');
    Route::get('customers/{customer}/edit', 'CustomerController@edit')->name('customers.edit');
    Route::get('customers/{customer}/update', 'CustomerController@update')->name('customers.update');

    Route::get('deliveries/report', 'DeliveryController@report')->name('deliveries.report');
    Route::resource('deliveries', 'DeliveryController');
    Route::get('deliveries/{delivery}/report', 'DeliveryController@printDetail')->name('deliveries.show.report');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['status'];
	protected $appends=['label_status','tanggal_pesan'];

    public function generateCode()
    {
        $monthyear = date('my');
        $currentCode = '/BKS/UTM/'.$monthyear;

        $last = Self::where('invoice_code', 'LIKE', '%'.$currentCode)->latest()->first();

        if(is_null($last)){
            $code = '00001'.$currentCode;
        }else{
            $lastNum = (int) substr($last->invoice_code, 1, 5);
            $code = sprintf("%'05d", $lastNum+1).$currentCode;
        }

        return $code;
    }

    public function getEstimatedDay($orders)
    {
        $production = Self::with(['details'])->where('status', '<', 2)->get();
        $totalQueueProductions = $production->map(function ($order){
            $order->total_size = $order->details->map(function($detail){
                $detail->total_size = $detail->product_size * $detail->quantity;
                return $detail;
            })->sum('total_size');
            return $order;
        })->sum('total_size');
        $sum = (int) $totalQueueProductions;
        foreach ($orders as $key => $value) {
            $order = (object) $value;
            $liter = $order->product_size * $order->quantity;
            $sum += $liter;
        }
        $estimated_day = 2 + ceil($sum/config('app.max_production'));
        return (int) $estimated_day;
    }

    public function details()
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function delivery()
    {
        return $this->hasOne(DeliveryDetail::class);
    }

    public function getLabelStatusAttribute()
    {
    	switch ($this->status) {
    		case 0:
    			return '<span class="badge badge-warning">Menunggu Produksi</span>';
    		case 1:
    			return '<span class="badge badge-primary">Produksi</span>';
    		case 2:
    			return '<span class="badge badge-info">Siap kirim</span>';
    		case 3:
    			return '<span class="badge badge-success">Dikirim</span>';
    	}
    }

    public function getTanggalPesanAttribute()
    {
        return $this->created_at->isoFormat('dddd, D MMMM Y HH:mm');
    }

    public function getTotalHargaAttribute(){
        return "Rp. " . number_format($this->total_price, 0, ',', '.');
    }

    public function getLabelTypeAttribute()
    {
    	if($this->type == 'offline'){
            return '<span class="badge badge-secondary">Offline</span>';
        }else{
            return '<span class="badge badge-light">Online</span>';
        }
    }
}

app/Models/OrderDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class OrderDetail extends Model
{
	protected $fillable = [
		'product_variant_id','product_name','product_size','quantity','price','sub_total_price','from_stock'
	];

    protected $guarderd = [];

    public function getHargaAttribute(){
        return "Rp. " . number_format($this->price, 0, ',', '.');
    }

    public function getSubTotalHargaAttribute(){
        return "Rp. " . number_format($this->sub_total_price, 0, ',', '.');
    }

    public function productVariant()
    {
        return $this->belongsTo(ProductVariant::class);
    }
}

app/Models/Production.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Production extends Model
{
    protected $appends = ['label_status','tanggal_produksi','label_type'];

    public function details()
    {
        return $this->hasMany(ProductionDetail::class);
    }

    public function generateCode()
    {
        $monthyear = date('my');
        $currentCode = '/BKS/PRD/'.$monthyear;

        $last = Self::where('code', 'LIKE', '%'.$currentCode)->latest()->first();

        if(is_null($last)){
            $code = '00001'.$currentCode;
        }else{
            $lastNum = (int) substr($last->code, 1, 5);
            $code = sprintf("%'05d", $lastNum+1).$currentCode;
        }

        return $code;
    }

    public function getTanggalProduksiAttribute()
    {
        return $this->created_at->isoFormat('dddd, D MMMM Y HH:mm');
    }

    public function getLabelStatusAttribute()
    {
    	switch ($this->status) {
    		case 0:
    			return '<span class="badge badge-warning">Menunggu Pengadaan</span>';
            case 1:
                return '<span class="badge badge-info">Menunggu Penerimaan Pengadaan</span>';
    		case 2:
    			return '<span class="badge badge-dark">Siap Produksi</span>';
            case 3:
                return '<span class="badge badge-primary">Sedang Produksi</span>';
    		case 4:
    			return '<span class="badge badge-success">Selesai</span>';
    	}
    }

    public function getLabelTypeAttribute()
    {
    	if($this->type == 'stock'){
            return '<span class="badge badge-secondary">Stock</span>';
        }else{
            return '<span class="badge badge-light">Pesanan</span>';
        }
    }

    public function getEstimatedDaysAttribute()
    {
        return 1 + ceil($this->total_size/config('app.max_production'));
    }

    public function order()
    {
        return $this->belongsTo(Order::class);
    }
}

resources/views/order/index.blade.php
@extends('layouts.default')
@section('css')
<link rel="stylesheet" href="{{asset('/stisla-2.2.0/dist/assets/modules/bootstrap-daterangepicker/daterangepicker.css')}}">
@endsection
@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Pesanan</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="#">Pesanan</a></div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4>Daftar Pesanan</h4>
              </div>
              <div class="card-body">
                <div class="float-left d-flex">
                    <a href="{{ route('orders.create') }}" class="btn btn-primary mr-2">Tambah Pesanan</a>
                    <button onclick="report()" class="btn btn-success">Laporan Pesanan</button>
                </div>
                <div class="float-right">
                  <form action="" method="GET" >
                    <div class="input-group">
                      @if(request()->daterange)
                        @php
                        $daterange=explode(" - ", request()->daterange);
                        $date_from = \Carbon\Carbon::createFromFormat('d/m/Y', $daterange[0]);
                        $date_to = \Carbon\Carbon::createFromFormat('d/m/Y', $daterange[1]);

                        $from = $date_from->format('d/m/Y');
                        $to = $date_to->format('d/m/Y');
                        @endphp
                        <input type="text" class="form-control daterange-cus mr-2" name="daterange" id="daterange" value="{{ $from }} - {{ $to }}">
                      @else
                      <input type="text" class="form-control daterange-cus mr-2" name="daterange" id="daterange" value="{{ date('d/m/Y', strtotime('-1 months'))}} - {{date("d/m/Y")}}">
                      @endif
                      <input type="text" class="form-control" name="search" placeholder="Search">
                      <div class="input-group-append">
                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                      </div>
                    </div>
                  </form>
                </div>

                <div class="clearfix mb-3"></div>

                <div class="table-responsive">
                  <table class="table table-striped">
                    <tr>
                      <th>No</th>
                      <th>Kode Pesanan</th>
                      <th>Nama Pemesan</th>
                      <th>Total Harga</th>
                      <th>Status</th>
                      <th>Tipe</th>
                      <th>#</th>
                    </tr>
                    @forelse ($orders as $item)
                    <tr>
                        <td>{{ (($orders->currentPage()-1) * $orders->perPage()) + $loop->iteration }}</td>
                        <td>{{ $item->invoice_code }}</td>
                        <td>{{ $item->customer_name }}</td>
                        <td>{{ $item->total_harga }}</td>
                        <td>{!! $item->label_status !!}</td>
                        <td>{!! $item->label_type !!}</td>
                        <td>
                            <a href="{{ route('orders.show', $item) }}" class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Lihat Pesanan"> <span class="fa fa-eye"></span></a>
                            {{-- <a href="{{ route('orders.edit', $item) }}" class="btn btn-sm btn-warning" data-toggle="tooltip" data-placement="top" title="Edit Pesanan"> <span class="fa fa-edit"></span></a> --}}
                            @if($item->status == 2 OR $item->status == 2)
                            <span data-title="{{ $item->customer_name }}" href="{{ route('orders.destroy', $item) }}" class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip" data-placement="top" title="Hapus Pesanan"> <span class="fa fa-trash"></span></span>
                            @endif
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" align="center">
                            <div class="empty-state" data-height="400" style="height: 400px;">
                                <div class="empty-state-icon">
                                  <i class="fas fa-question"></i>
                                </div>
                                <h2>Data Tidak Ditemukan</h2>
                                <p class="lead">
                                  Maaf kami tidak dapat menemukan data.
                                </p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
                <div class="float-right">
                  {{ $orders->links() }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

<form action="" method="POST" id="deleteForm">
    @csrf
    @method('DELETE')
    <input type="submit" style="display: none;">
</form>
@endsection

@section('js')
<script src="{{asset('/stisla-2.2.0/dist/assets/modules/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<script type="text/javascript">
  $('.daterange-cus').daterangepicker({
    locale: {format: 'DD/MM/YYYY'},
    drops: 'down',
    opens: 'left'
  });

</script>
<script type="text/javascript">
    $('.btn-delete').on('click', function(){
        var href = $(this).attr('href');
        var title = $(this).data('title');
        swal({
          title: "Anda yakin akan menghapus Pesanan atas nama "+ title +" ?",
          text: "Setelah dihapus data tidak dapat dikembalikan !",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $('#deleteForm').attr('action', href);
            $('#deleteForm').submit();
          }
        });
    });

    function submitForm()
    {
        console.log('change')
    }
    function report(){
        daterange = $('#daterange').val()
        url = `{{url('orders')}}/report?daterange=${daterange}`
        window.location = url
    }
    </script>
@endsection

resources/views/order/show.blade.php
@extends('layouts.default')

@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('orders.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Detail Pesanan</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
          <div class="breadcrumb-item"><a href="{{ route('orders.index') }}">Pesanan</a></div>
          <div class="breadcrumb-item">Detail Pesanan</div>
        </div>
      </div>
      <div class="section-body">
        <div class="row mt-4">
          <div class="col-12">
            <div class="card">
                <div class="card-header">
                  <h4>Invoice : {{$order->invoice_code }}</h4>
                  <div class="card-header-action">
                    <a href="{{route('orders.show.report', $order)}}" class="btn btn-success mr-1">
                        Cetak
                    </a>
                    @if(\Auth::user()->role == 'administrator' || \Auth::user()->role == 'bag_produksi')
                        @switch($order->status)
                            @case(0)
                                <a href="{{ route('orders.toggle_status', $order) }}?status=1" class="btn btn-primary">
                                    Produksi
                                </a>
                                @break
                        @endswitch
                    @endif
                  </div>
                </div>
                <div class="card-body">
                  <div class="row mb-2">
                    <div class="col-md-6">
                      <b>Alamat Pengiriman</b><br>
                      {{ $order->customer_name }}<br>
                      {{ $order->customer_phone }}<br>
                      {{ $order->customer_address }}
                    </div>
                    <div class="col-md-3">
                      <b>Estimasi Waktu</b><br>
                      {{ $order->estimated_days }} Hari<br><br>
                      <b>Total Harga</b><br>
                      {{ $order->total_harga }}
                    </div>
                    <div class="col-md-3">
                      <b>Status Pesanan</b><br>
                      {!! $order->label_status !!}<br><br>
                      <b>Tipe</b><br>
                      {!! $order->label_type !!}
                    </div>
                  </div>
                </div>
            </div>

            <div class="card">
              <div class="card-header">
                <h4>Data Produk</h4>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered">
                    <tr>
                      <th>No</th>
                      <th>Nama Produk</th>
                      <th>Ukuran Produk</th>
                    @if(\Auth::user()->role == 'administrator' || \Auth::user()->role == 'bag_produksi')
                      <th>Dari Stock</th>
                    @endif
                      <th>Qty</th>
                      <th>Harga</th>
                      <th>Sub Total</th>
                    </tr>
                    @php $no = 1 @endphp
                    @forelse ($products as $product => $details)
                        @foreach ($details as $key => $item)
                        <tr >
                            @if ($key == 0)
                            <td rowspan="{{ count($details) }}">{{ $no }}</td>
                            <td rowspan="{{ count($details) }}">{{ $item->product_name }}</td>
                            @endif
                            <td>{{ $item->product_size }} Liter</td>
                            @if(\Auth::user()->role == 'administrator' || \Auth::user()->role == 'bag_produksi')
                            <td>{{ $item->from_stock}}</td>
                            @endif
                            <td>{{ $item->quantity }}</td>
                            <td>{{ $item->harga}}</td>
                            <td>{{ $item->sub_total_harga}}</td>
                        </tr>
                        @endforeach
                        @php $no++ @endphp
                    @empty
                    <tr>
                        <td colspan="4" align="center">
                            <div class="empty-state" data-height="400" style="height: 400px;">
                                <div class="empty-state-icon">
                                  <i class="fas fa-question"></i>
                                </div>
                                <h2>Data Tidak Ditemukan</h2>
                                <p class="lead">
                                  Maaf kami tidak dapat menemukan data.
                                </p>
                            </div>
                        </td>
                    </tr>
                    @endforelse
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </section>
  </div>
@endsection

@section('js')

@endsection